"""Agent Purchase Protection exposure book — the money slide.

On 14 April 2026 American Express committed to covering charges arising from *registered
agent error*. It took on the liability before publishing any machinery to price or cap it.
This module is that machinery: it turns the registry's behavioural telemetry into an
expected-loss number per operator, a portfolio total, and an admission curve an
underwriter can actually set policy from — "at risk-score cutoff 60 we admit 82% of agent
volume and cap modelled governed exposure at ₹X".

The model, in full, per operator:

    covered_volume   = authorized_volume × coverage_share
    error_rate       = smoothed(agent-error attempts ÷ decisions)      [from telemetry]
    ungoverned_loss  = covered_volume × error_rate × severity
    governed_loss    = ungoverned_loss × residual_leakage
    prevented        = ungoverned_loss − governed_loss
    stressed_loss    = governed_loss × stress_multiplier

`ungoverned_loss` is what the same agent traffic would cost with no mandate layer: every
agent-error attempt becomes a charge Agent Purchase Protection has to eat. `governed_loss`
is what survives CAVEAT. We do **not** claim the difference is zero-risk — `residual_leakage`
is an explicit assumption that says what share of agent-error attempts we assume slip past
the governance layer anyway, and it is the single most load-bearing number in this file.

Note on the two sides of the arithmetic, because it is the first thing an underwriter will
ask: the base is *authorized* volume, while the rate comes from *denied* decisions. That is
deliberate. An agent-error attempt CAVEAT blocked never became a charge, so it contributes
to how often this operator strays, not to how much money it moved. The model reads as "for
every rupee this operator successfully put through, here is the rate at which its behaviour
left its mandate, and here is what that behaviour would cost if it reached settlement".

All arithmetic is integer: minor units (paise) for money, basis points for rates. No float
enters a monetary calculation.

HONESTY REQUIREMENT — read this before quoting any number out of this module:

  * This is a **model over synthetic telemetry generated by this prototype**, not a
    measurement of anything. The rates come from decisions our own mock agents made
    against our own mock merchants.
  * Every coefficient (severity, residual leakage, the cold-start prior, the stress
    multiplier, coverage share) is an assumption we invented and named. They are carried
    in the output as `assumptions` so no chart can be screenshotted without them.
  * **No real American Express loss, fraud or coverage figure appears anywhere here**, and
    none should be substituted without saying so. The contribution is the method and the
    plumbing from live governance telemetry into it — not the coefficients.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Sequence

from .constraints import (
    REASON_CATEGORY_NOT_ALLOWED,
    REASON_MCC_NOT_ALLOWED,
    REASON_MERCHANT_NOT_ALLOWED,
    fmt_money,
)
from .pdp import (
    REASON_CART_DIVERGENCE,
    REASON_MANDATE_REVOKED,
    REASON_MERCHANT_SWAPPED,
)
from .registry import (
    SIGNAL_DENIED,
    AgentRegistry,
    RiskAssessment,
)
from .store import Store

BP = 10_000  # one hundred percent, in basis points

DISCLAIMER = (
    "Model over synthetic prototype telemetry, not a measurement. Every coefficient below "
    "is a named assumption chosen by the CAVEAT team; none is an American Express figure."
)

# Reason codes that route liability to Agent Purchase Protection, mirroring the scope
# breaches in pdp.classify_liability.
AGENT_ERROR_REASONS = frozenset(
    {
        REASON_MCC_NOT_ALLOWED,
        REASON_MERCHANT_NOT_ALLOWED,
        REASON_CATEGORY_NOT_ALLOWED,
        REASON_MANDATE_REVOKED,
    }
)

# Reasons that pdp.classify_liability tests *before* the scope breaches, and which route
# liability elsewhere (fraud, or the merchant). Their presence means the decision is not
# agent error no matter what else it carries.
PREEMPTING_REASONS = frozenset({REASON_MERCHANT_SWAPPED, REASON_CART_DIVERGENCE})


def is_agent_error_attempt(reason_codes: Sequence[str]) -> bool:
    """Would pdp.classify_liability have called this AGENT_ERROR, from reason codes alone?

    Faithful to that function's precedence: a cart that moved after signature is fraud or
    merchant misrepresentation and is charged to neither the operator nor Agent Purchase
    Protection, whatever scope it also broke. Reason codes are sufficient to decide the
    AGENT_ERROR case exactly, because both divergence branches return other verdicts.

    Applies to denied decisions. REASON_MANDATE_REVOKED only reaches AGENT_ERROR on a DENY
    in classify_liability, and a revoked root always hard-denies, so callers that filter to
    denials — which is all of them here — get the same answer.
    """
    codes = set(reason_codes)
    if codes & PREEMPTING_REASONS:
        return False
    return bool(codes & AGENT_ERROR_REASONS)


@dataclass(frozen=True)
class ExposureAssumptions:
    """Every coefficient in the model, named, documented and overridable.

    Rates are basis points so the whole model stays in integer arithmetic.
    """

    # Share of an operator's authorized volume that falls under Agent Purchase Protection.
    # 10_000 bp = all of it; lower it to model partial coverage or a deductible tier.
    coverage_share_bp: int = 10_000

    # Loss given an agent-error charge, as a share of the transaction value, net of
    # recovery from the merchant. Placeholder — chargeback recovery on agentic disputes is
    # exactly what nobody has data for yet.
    severity_bp: int = 6_000

    # Share of agent-error attempts assumed to slip past the governance layer and become
    # covered charges anyway. THE load-bearing assumption: it is what stops this model
    # claiming that governance drives residual risk to zero.
    residual_leakage_bp: int = 500

    # Cold-start prior for an operator's agent-error rate, and its weight in
    # pseudo-decisions. A brand-new operator is priced at the prior, not at zero.
    baseline_agent_error_rate_bp: int = 150
    prior_weight_decisions: int = 5

    # Stress view: multiple of expected loss held as a capital/limit planning number.
    stress_multiplier_bp: int = 30_000

    # Operators above this risk score are excluded from the book entirely, matching the
    # registry's suspended band.
    admission_cutoff_default: int = 80

    def to_dict(self) -> dict[str, Any]:
        return {
            "coverage_share_bp": self.coverage_share_bp,
            "severity_bp": self.severity_bp,
            "residual_leakage_bp": self.residual_leakage_bp,
            "baseline_agent_error_rate_bp": self.baseline_agent_error_rate_bp,
            "prior_weight_decisions": self.prior_weight_decisions,
            "stress_multiplier_bp": self.stress_multiplier_bp,
            "admission_cutoff_default": self.admission_cutoff_default,
            "disclaimer": DISCLAIMER,
        }

    def describe(self) -> list[str]:
        return [
            f"coverage share            {self.coverage_share_bp / 100:.2f}% of authorized volume is covered",
            f"severity                  {self.severity_bp / 100:.2f}% of a covered charge is lost net of recovery",
            f"residual leakage          {self.residual_leakage_bp / 100:.2f}% of agent-error attempts assumed to slip past CAVEAT",
            f"cold-start error rate     {self.baseline_agent_error_rate_bp / 100:.2f}% prior, weighted as {self.prior_weight_decisions} decisions",
            f"stress multiplier         {self.stress_multiplier_bp / BP:.2f}× expected loss",
            f"default admission cutoff  risk score ≤ {self.admission_cutoff_default}",
            f"NOTE: {DISCLAIMER}",
        ]


@dataclass(frozen=True)
class OperatorExposure:
    """One operator's line in the book. All money is integer minor units."""

    operator_id: str
    name: str
    registered: bool
    risk_score: float
    band: str
    decisions: int
    agent_error_attempts: int
    agent_error_rate_bp: int
    authorized_volume_minor: int
    covered_volume_minor: int
    ungoverned_expected_loss_minor: int
    expected_loss_minor: int
    prevented_loss_minor: int
    stressed_loss_minor: int
    suggested_exposure_cap_minor: int

    @property
    def loss_rate_bp(self) -> int:
        """Modelled governed loss per unit of covered volume, in basis points."""
        if self.covered_volume_minor <= 0:
            return 0
        return self.expected_loss_minor * BP // self.covered_volume_minor

    def to_dict(self) -> dict[str, Any]:
        return {
            "operator_id": self.operator_id,
            "name": self.name,
            "registered": self.registered,
            "risk_score": round(self.risk_score, 2),
            "band": self.band,
            "decisions": self.decisions,
            "agent_error_attempts": self.agent_error_attempts,
            "agent_error_rate_bp": self.agent_error_rate_bp,
            "authorized_volume_minor": self.authorized_volume_minor,
            "authorized_volume_display": fmt_money(self.authorized_volume_minor),
            "covered_volume_minor": self.covered_volume_minor,
            "ungoverned_expected_loss_minor": self.ungoverned_expected_loss_minor,
            "expected_loss_minor": self.expected_loss_minor,
            "expected_loss_display": fmt_money(self.expected_loss_minor),
            "prevented_loss_minor": self.prevented_loss_minor,
            "prevented_loss_display": fmt_money(self.prevented_loss_minor),
            "stressed_loss_minor": self.stressed_loss_minor,
            "loss_rate_bp": self.loss_rate_bp,
            "suggested_exposure_cap_minor": self.suggested_exposure_cap_minor,
        }


@dataclass(frozen=True)
class CutoffPoint:
    """What admitting everyone at or below `cutoff` costs and buys."""

    cutoff: int
    admitted_operators: int
    total_operators: int
    admitted_volume_minor: int
    total_volume_minor: int
    expected_loss_minor: int
    ungoverned_expected_loss_minor: int
    stressed_loss_minor: int

    @property
    def admitted_volume_share_bp(self) -> int:
        if self.total_volume_minor <= 0:
            return 0
        return self.admitted_volume_minor * BP // self.total_volume_minor

    @property
    def loss_rate_bp(self) -> int:
        if self.admitted_volume_minor <= 0:
            return 0
        return self.expected_loss_minor * BP // self.admitted_volume_minor

    def headline(self) -> str:
        return (
            f"at cutoff {self.cutoff} we admit {self.admitted_operators}/{self.total_operators} "
            f"operators and {self.admitted_volume_share_bp / 100:.1f}% of volume, "
            f"modelled exposure {fmt_money(self.expected_loss_minor)}"
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "cutoff": self.cutoff,
            "admitted_operators": self.admitted_operators,
            "total_operators": self.total_operators,
            "admitted_volume_minor": self.admitted_volume_minor,
            "total_volume_minor": self.total_volume_minor,
            "admitted_volume_share_bp": self.admitted_volume_share_bp,
            "expected_loss_minor": self.expected_loss_minor,
            "expected_loss_display": fmt_money(self.expected_loss_minor),
            "ungoverned_expected_loss_minor": self.ungoverned_expected_loss_minor,
            "stressed_loss_minor": self.stressed_loss_minor,
            "loss_rate_bp": self.loss_rate_bp,
            "headline": self.headline(),
        }


DEFAULT_CUTOFFS: tuple[int, ...] = (0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)


@dataclass(frozen=True)
class ExposureBook:
    generated_at: int
    assumptions: ExposureAssumptions
    entries: tuple[OperatorExposure, ...]
    curve: tuple[CutoffPoint, ...]

    @property
    def total_volume_minor(self) -> int:
        return sum(e.authorized_volume_minor for e in self.entries)

    @property
    def total_expected_loss_minor(self) -> int:
        return sum(e.expected_loss_minor for e in self.entries)

    @property
    def total_ungoverned_loss_minor(self) -> int:
        return sum(e.ungoverned_expected_loss_minor for e in self.entries)

    @property
    def total_prevented_loss_minor(self) -> int:
        return sum(e.prevented_loss_minor for e in self.entries)

    def point_at(self, cutoff: int) -> CutoffPoint | None:
        for p in self.curve:
            if p.cutoff == cutoff:
                return p
        return None

    @property
    def recommended(self) -> CutoffPoint | None:
        """The curve point at the assumptions' default admission cutoff.

        `ExposureModel.book` always plots that cutoff, so this is never None for a book
        built through it.
        """
        return self.point_at(self.assumptions.admission_cutoff_default)

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at": self.generated_at,
            "assumptions": self.assumptions.to_dict(),
            "assumption_notes": self.assumptions.describe(),
            "entries": [e.to_dict() for e in self.entries],
            "curve": [p.to_dict() for p in self.curve],
            "totals": {
                "operators": len(self.entries),
                "volume_minor": self.total_volume_minor,
                "volume_display": fmt_money(self.total_volume_minor),
                "expected_loss_minor": self.total_expected_loss_minor,
                "expected_loss_display": fmt_money(self.total_expected_loss_minor),
                "ungoverned_expected_loss_minor": self.total_ungoverned_loss_minor,
                "prevented_loss_minor": self.total_prevented_loss_minor,
                "prevented_loss_display": fmt_money(self.total_prevented_loss_minor),
            },
            "disclaimer": DISCLAIMER,
        }

    def render_text(self, width: int = 96) -> str:
        rule = "═" * width
        thin = "─" * width
        out = [
            rule,
            "AGENT PURCHASE PROTECTION — MODELLED EXPOSURE BOOK".center(width),
            f"generated at {self.generated_at}".center(width),
            rule,
            "",
            f"  book volume            {fmt_money(self.total_volume_minor)}",
            f"  ungoverned exposure    {fmt_money(self.total_ungoverned_loss_minor)}   (no mandate layer)",
            f"  governed exposure      {fmt_money(self.total_expected_loss_minor)}   (behind CAVEAT)",
            f"  modelled prevention    {fmt_money(self.total_prevented_loss_minor)}",
            "",
            thin,
            "PER OPERATOR",
            thin,
            f"  {'operator':<22}{'band':<12}{'score':>6}  {'volume':>14}{'err bp':>8}{'exposure':>14}",
        ]
        for e in self.entries:
            out.append(
                f"  {e.operator_id:<22}{e.band:<12}{e.risk_score:>6.1f}  "
                f"{fmt_money(e.authorized_volume_minor):>14}{e.agent_error_rate_bp:>8}"
                f"{fmt_money(e.expected_loss_minor):>14}"
            )
        out += [
            "",
            thin,
            "ADMISSION CUTOFF CURVE  (admit operators with risk score ≤ cutoff)",
            thin,
            f"  {'cutoff':>6}{'ops':>6}{'volume admitted':>18}{'share':>9}{'exposure':>16}{'stressed':>16}",
        ]
        for p in self.curve:
            out.append(
                f"  {p.cutoff:>6}{p.admitted_operators:>6}"
                f"{fmt_money(p.admitted_volume_minor):>18}"
                f"{p.admitted_volume_share_bp / 100:>8.1f}%"
                f"{fmt_money(p.expected_loss_minor):>16}"
                f"{fmt_money(p.stressed_loss_minor):>16}"
            )
        out += ["", thin, "ASSUMPTIONS", thin]
        for line in self.assumptions.describe():
            out.append(f"  {line}")
        out.append(rule)
        return "\n".join(out)


def authorized_volume_by_operator(store: Store) -> dict[str, int]:
    """Sum authorized spend per mandate holder, in integer minor units.

    Joins `authorizations` to `mandates` on mandate_id, so volume is attributed to the
    operator that actually held the credential at authorization time rather than to the
    root grant's holder.
    """
    holder_by_mandate: dict[str, str] = {}
    root_ids: set[str] = set()
    for row in store.all_mandates():
        holder_by_mandate[row["mandate_id"]] = row["holder"]
        root_ids.add(row["root_id"])

    out: dict[str, int] = {}
    for root_id in sorted(root_ids):
        for auth in store.authorizations_for_root(root_id):
            holder = holder_by_mandate.get(auth.mandate_id)
            if holder is None:
                continue
            out[holder] = out.get(holder, 0) + auth.amount
    return out


def agent_error_attempts(store: Store, operator_id: str) -> int:
    """Count denials this operator caused that classify as registered-agent error.

    Reads the reason codes the engine stored on each `denied` event, so the count is
    telemetry rather than an assumption.
    """
    n = 0
    for event in store.operator_events(operator_id):
        if event["event"] != SIGNAL_DENIED:
            continue
        if is_agent_error_attempt(event.get("detail", {}).get("reasons", [])):
            n += 1
    return n


def smoothed_rate_bp(count: int, denominator: int, *, prior_bp: int, prior_weight: int) -> int:
    """Shrink an observed rate toward a prior, in integer basis points.

    Integer throughout: `(count·10000 + prior_weight·prior_bp) / (denominator + prior_weight)`.
    """
    total = denominator + prior_weight
    if total <= 0:
        return min(BP, max(0, prior_bp))
    rate = (count * BP + prior_weight * prior_bp) // total
    return min(BP, max(0, rate))


class ExposureModel:
    """Prices the registry's telemetry into an underwritable book."""

    def __init__(
        self,
        registry: AgentRegistry,
        assumptions: ExposureAssumptions | None = None,
    ) -> None:
        self.registry = registry
        self.store = registry.store
        self.assumptions = assumptions or ExposureAssumptions()

    # -- one operator ------------------------------------------------------------------

    def price(
        self,
        assessment: RiskAssessment,
        *,
        authorized_volume_minor: int,
    ) -> OperatorExposure:
        a = self.assumptions
        attempts = agent_error_attempts(self.store, assessment.operator_id)
        rate_bp = smoothed_rate_bp(
            attempts,
            assessment.decisions,
            prior_bp=a.baseline_agent_error_rate_bp,
            prior_weight=a.prior_weight_decisions,
        )

        covered = authorized_volume_minor * a.coverage_share_bp // BP
        # One division so truncation happens once, not three times.
        ungoverned = covered * rate_bp * a.severity_bp // (BP * BP)
        governed = ungoverned * a.residual_leakage_bp // BP
        stressed = governed * a.stress_multiplier_bp // BP

        return OperatorExposure(
            operator_id=assessment.operator_id,
            name=assessment.name,
            registered=assessment.registered,
            risk_score=assessment.score,
            band=assessment.band,
            decisions=assessment.decisions,
            agent_error_attempts=attempts,
            agent_error_rate_bp=rate_bp,
            authorized_volume_minor=authorized_volume_minor,
            covered_volume_minor=covered,
            ungoverned_expected_loss_minor=ungoverned,
            expected_loss_minor=governed,
            prevented_loss_minor=ungoverned - governed,
            stressed_loss_minor=stressed,
            suggested_exposure_cap_minor=assessment.suggested_exposure_cap_minor,
        )

    # -- the book ----------------------------------------------------------------------

    def book(
        self,
        *,
        now: int,
        volume_overrides: Mapping[str, int] | None = None,
        cutoffs: Sequence[int] = DEFAULT_CUTOFFS,
        operator_ids: Sequence[str] | None = None,
    ) -> ExposureBook:
        """Price every known operator and lay out the admission curve.

        `volume_overrides` lets an analyst ask "what if this operator ran ₹10 crore" without
        fabricating transactions; anything not overridden comes from real authorizations.
        """
        volumes = authorized_volume_by_operator(self.store)
        if volume_overrides:
            volumes = {**volumes, **dict(volume_overrides)}

        assessments = self.registry.portfolio(now=now, operator_ids=operator_ids)
        entries = tuple(
            self.price(a, authorized_volume_minor=volumes.get(a.operator_id, 0))
            for a in assessments
        )
        # The default admission cutoff is always plotted, so `ExposureBook.recommended`
        # resolves whatever grid the caller asked for.
        plotted = sorted(set(cutoffs) | {self.assumptions.admission_cutoff_default})
        curve = tuple(self._cutoff_point(entries, cutoff) for cutoff in plotted)
        return ExposureBook(
            generated_at=now,
            assumptions=self.assumptions,
            entries=entries,
            curve=curve,
        )

    def _cutoff_point(self, entries: Sequence[OperatorExposure], cutoff: int) -> CutoffPoint:
        admitted = [e for e in entries if e.risk_score <= cutoff]
        return CutoffPoint(
            cutoff=cutoff,
            admitted_operators=len(admitted),
            total_operators=len(entries),
            admitted_volume_minor=sum(e.authorized_volume_minor for e in admitted),
            total_volume_minor=sum(e.authorized_volume_minor for e in entries),
            expected_loss_minor=sum(e.expected_loss_minor for e in admitted),
            ungoverned_expected_loss_minor=sum(e.ungoverned_expected_loss_minor for e in admitted),
            stressed_loss_minor=sum(e.stressed_loss_minor for e in admitted),
        )
